name: Generate links for folders in README
on: [push]
# ©Nayeem Hossain.All rights reserved
jobs:
  generate_links:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get links for folders
      run: |
        TOKEN=${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 1)
        REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)
        echo -e "" > README.md
        echo "<h2> Question Bank</h2>
<b><h4>Inspiration:</h4></b>

We all need questions from previous semesters of previous batches to learn or practice the question pattern of a course. Especially first year students need more. It takes a lot of time to understand about the exam. It is much easier to practice if you have previous year's questions.We allways face trouble to collect questions in time. We hope this repository will help us.

<b><h4>How to attach a question:</h></b>
[Contribution](https://github.com/CoUCSE/Question-Bank/blob/main/Contribution.md)" >> README.md
        function build_tree {
            local path=$1
            local indent=$2
            local contents=$(curl -s -H "Authorization: token $TOKEN" "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/contents/$path")
            local folders=$(echo $contents | jq -r '.[] | select(.type == "dir")')
            local last_folder=""
            for folder in $(echo "${folders}" | jq -r '.name'); do
                if [ "$folder" != ".github" ]; then
                  local folder_path=$path/$folder
                  echo -e "${indent}* [${folder}](https://github.com/$REPO_OWNER/$REPO_NAME/tree/main/${folder_path})" >> README.md
                  last_folder=$folder
                  build_tree $folder_path "${indent}\t"
                fi
            done
        }
        echo -e "" >> README.md
        build_tree "" ""
    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "GitHub Actions"
        git add README.md
        git commit -m "Update README with links for folders"
        git push